<header>
    <meta name="csrf-token" content="{{ csrf_token() }}">
</header>
@extends('layouts.app')


@push('styles')
<link rel="stylesheet" href="{{ asset('vendor/full-calendar/main.min.css') }}">
<link rel="stylesheet" href="{{ asset('vendor/css/bootstrap-colorpicker.css') }}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
@endpush

@push('datatable-styles')
@include('sections.daterange_css')
@endpush

@section('content')
<div class="content-wrapper">
    <div class="bg-white rounded b-shadow-4 create-inv">
        <div class="px-lg-4 px-md-4 px-3 py-3">
            <h4 class="mb-0 f-21 font-weight-normal text-capitalize">Create Order</h4>
        </div>
        <hr class="m-0 border-top-grey">
        <form>
            <div class="row px-lg-4 px-md-4 px-3 pt-3">
                <div class="col-md-4 mb-4">
                    <div class="form-group mb-lg-0 mb-md-0 mb-4">
                        <label class="f-14 text-dark-grey mb-12">Order Number<sup class="f-14 mr-1">*</sup></label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">order number</span>
                            </div>
                            <input type="text" name="order_number" id="order_number" class="form-control height-35 f-15" value="1" autocomplete="off">
                        </div>
                    </div>
                </div>
                <div class="col-md-4 mb-4">
                    <div class="form-group mb-lg-0 mb-md-0 mb-4">
                        <label class="f-14 text-dark-grey mb-12">Client<sup class="f-14 mr-1">*</sup></label>
                        <div class="input-group">
                            <div class="dropdown bootstrap-select form-control select-picker">
                                <select class="form-control select-picker" data-live-search="true" data-size="8" name="client_id" id="client_list_id" tabindex="null">
                                    <option value="">--</option>
                                </select>
                            </div>
                            <div class="input-group-append">
                                <a href="#" id="quick-create-client" data-toggle="tooltip" data-original-title="Add New Client" class="btn btn-outline-secondary border-grey">Add</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 mb-4">
                    <div class="form-group c-inv-select mb-0">
                        <label class="f-14 text-dark-grey mb-12 text-capitalize w-100" for="usr">Billing Address</label>
                        <p class="f-15" id="client_billing_address">
                            <span class="text-lightest">billing should be fetched after client selection</span>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group c-inv-select mb-lg-0 mb-md-0 mb-4">
                        <label class="f-14 text-dark-grey mb-12 text-capitalize w-100" for="usr">Shipping Address </label>
                        <a href="#" class="text-capitalize" id="show-shipping-field"> <i class="fa fa-plus mr-2"></i>Add Shipping Address</a>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group c-inv-select mb-4">
                        <label class="f-14 text-dark-grey mb-12" data-label="" for="company_address_id">Generated By </label>
                        <div class="select-others height-35 rounded">
                            <div class="dropdown bootstrap-select form-control select-picker">
                                <select class="form-control select-picker">
                                    <option>-----</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <label class="f-14 text-dark-grey mb-12 mt-0" data-label="1" for="status">Status
                        <sup class="f-14 mr-1">*</sup>

                    </label>

                    <div class="dropdown bootstrap-select form-control select-picker"><select class="form-control select-picker" name="status" id="status">
                            <option value="pending" data-content="<i class='fa fa-circle mr-2 text-yellow'></i> Pending ">Pending</option>

                            <option value="on-hold" data-content="<i class='fa fa-circle mr-2 text-info'></i> On Hold ">On Hold</option>

                            <option value="failed" data-content="<i class='fa fa-circle mr-2 text-muted'></i> Failed ">Failed</option>

                            <option value="processing" data-content="<i class='fa fa-circle mr-2 text-blue'></i> Processing ">Processing</option>

                            <option value="completed" data-content="<i class='fa fa-circle mr-2 text-dark-green'></i> Completed ">Completed</option>

                            <option value="canceled" data-content="<i class='fa fa-circle mr-2 text-red'></i> Canceled ">Canceled</option>

                        </select>
                    </div>
                </div>
            </div>
            <hr class="m-0 mt-2 border-top-grey">
            <div class="row px-lg-4 px-md-4 px-3 py-3">
                <div class="col-md-3">
                    <div class="form-group c-inv-select mb-4">
                        <div class="input-group">
                            <div class="dropdown bootstrap-select form-control select-picker">
                                <select class="form-control select-picker" data-live-search="true" data-size="8" id="add-products" title="Select Product" tabindex="null">
                                    <option class="bs-title-option" value=""></option>
                                    <option>----</option>
                                </select>
                            </div>
                            <div class="input-group-append">
                                <a class="btn btn-outline-secondary border-grey toggle-product-category">
                                    <i class="fa fa-filter"></i></a>
                            </div>
                            <div class="input-group-append">
                                <a class="btn btn-outline-secondary border-grey openRightModal">Add</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <hr class="m-0 border-top-grey">
                <div class="d-flex px-lg-4 px-md-4 px-3 pb-3 c-inv-total">
                    <div style="width:100%;" class="d-flex">
                        <div style="width:50%;">
                        </div>
                        <div style="width:50%;" class="p-0 border-0 c-inv-total-right">
                            <table>
                                <tr>
                                    <td class="border-top-0 text-dark-grey" colspan="2">sub total</td>
                                    <td class="border-top-0 sub-total" width="30%">precent</td>
                                </tr>
                                <tr>
                                    <td width="20%" class="text-dark-grey">Discount</td>
                                    <td width="40%" style="padding: 5px;">
                                        <table width="100%">
                                            <tbody>
                                                <tr>
                                                    <td width="70%" class="c-inv-sub-padding">
                                                        <input class="form-control f-14 border-0 w-100 text-right discount_value">
                                                    </td>
                                                    <td width="30%" align="left" class="c-inv-sub-padding">
                                                        <div class="select-others select-tax height-35 rounded border-0">
                                                            <div class="dropdown bootstrap-select form-control select-picker"><select class="form-control select-picker" id="discount_type" name="discount_type">
                                                                    <option value="percent">%
                                                                    </option>
                                                                    <option value="fixed">
                                                                        Amount</option>
                                                                </select>
                                                                <button type="button" class="btn dropdown-toggle btn-light">
                                                                    <div class="filter-option">
                                                                        <div class="filter-option-inner">
                                                                            <div class="filter-option-inner-inner">%</div>
                                                                        </div>
                                                                    </div>
                                                                </button>
                                                                <div class="dropdown-menu ">
                                                                    <div class="inner show">
                                                                        <ul class="dropdown-menu inner show"></ul>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </td>
                                                    <td><span>0.00</span> </td>
                                                </tr>
                                                <tr>
                                                    <td>Tax</td>
                                                    <td colspan="2" class="p-0 border-0">
                                                        <table width="100%">
                                                            <tr>
                                                                <td colspan="2"><span class="tax-percent">0.00</span></td>
                                                            </tr>
                                                        </table>
                                                    </td>
                                                </tr>
                                                <tr class="bg-amt-grey f-16 f-w-500">
                                                    <td colspan="2">Total</td>
                                                    <td><span class="total">0.00</span></td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                                <tr>

                                </tr>
                            </table>
                        </div>
                        <div class="d-flex flex-wrap px-lg-4 px-md-4 px-3 py-3">
                            <div class="col-md-6 col-sm-12 c-inv-note-terms p-0 mb-lg-0 mb-md-0 mb-3">
                                <label class="f-14 text-dark-grey mb-12 text-capitalize w-100">Client Note</label>
                                <textarea class="form-control"></textarea>
                            </div>

                        </div>
                        <div class="w-100 border-top-grey d-block d-lg-flex d-md-flex justify-content-start px-4 py-3 c-inv-btns d-block d-lg-flex d-md-flex">
                            <button type="button" class="btn-primary rounded f-14 p-2" id="createOrder">
                                Submit
                            </button>
                            <input type="search" class="autocomplete-password" style="opacity: 0;position: absolute;" >
                            <input type="password" class="autocomplete-password" style="opacity: 0;position: absolute;" >
                            <input type="email"  class="autocomplete-password" readonly="" style="opacity: 0;position: absolute;" >
                            <input type="text" class="autocomplete-password" readonly="" style="opacity: 0;position: absolute;" >
                            <a  class="btn-cancel rounded f-14 p-2 ml-2 border-0">
                                Cancel
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection